== Using regular expressions with String methods

=== Redefined methods on String for processing regular expressions

`Strings`
in Java have built-in support for regular expressions.
`Strings`
have four built-in methods for regular expressions, i.e., the
`matches()`
,
`split())`
,
`replaceFirst()`
and
`replaceAll()`
methods. The
`replace()`
method does NOT support regular expressions.

These methods are not optimized for performance. We will later
use classes which are optimized for performance.

|===
|Method |Description

|`s.matches("regex")`
|Evaluates if `"regex"` matches `s`. 
Returns only `true` if the WHOLE string can be matched.

|`s.split("regex")`
|Creates an array with substrings of `s` divided at occurrence of `"regex"`.
`"regex"` is not included in the result.

|`s.replaceFirst("regex"), "replacement"`
|Replaces first occurance of `"regex"` with `"replacement"`.

|`s.replaceAll("regex"), "replacement"`
|Replaces all occurances of `"regex"` with `"replacement"`.
|===

Create for the following example the Java project
`de.vogella.regex.test`.

[source,java]
----
include::res/string/RegexTestStrings.java[]
----

=== Examples

The following class gives several examples for the usage of
regular expressions with strings. See the comment for the purpose.

If you want to test these examples, create for
the Java project
`de.vogella.regex.string`.

[source,java]
----
include::res/string/StringMatcher.java[]
----

And a small JUnit Test to validates the examples.

[source,java]
----
include::res/string/StringMatcherTest.java[]
----

