== Using OkHttp for efficient network access
(((OkHttp)))

=== What is OkHTTP?
OkHTTP (http://square.github.io/okhttp/) is an Open Source project designed to be an efficient HTTP client. 
It supports the SPDY protocol. 
SPDY is the basis for HTTP 2.0 and allows multiple HTTP requests to be multiplexed over one socket connection.

If you are using Maven or Gradle as build system you can simply add a
dependency to group ID `com.squareup.okhttp`, artifactId, `okhttp` and the version 2.1.0 (current as of this writing).

[source,gradle]
----
compile 'com.squareup.okhttp:okhttp:2.5.0'
----

NOTE: As of Android 5.0 OkHttp is part of the Android platform and is used for all HTTP calls.


=== Creating request objects for make network calls

To use OkHttp you need to create a `Request` object.

[source,java]
----
// avoid creating several instances, should be singleon
OkHttpClient client = new OkHttpClient();

Request request = new Request.Builder()
                     .url("http://www.vogella.com/index.html")
                     .build();
----

You can also add parameters

[source,java]
----
HttpUrl.Builder urlBuilder = HttpUrl.parse("https://api.github.help").newBuilder();
urlBuilder.addQueryParameter("v", "1.0");
urlBuilder.addQueryParameter("user", "vogella");
String url = urlBuilder.build().toString();

Request request = new Request.Builder()
                     .url(url)
                     .build();
----

You can also add authentication headers

[source,java]
----
Request request = new Request.Builder()
    .header("Authorization", "your token")
    .url("https://api.github.com/users/vogella")
    .build();
----

=== Sending and receiving network calls

To make a synchronous network call, use the `Client` to create a `Call` object and use the `execute` method.

[source,java]
----
Response response = client.newCall(request).execute();
----

To make asynchronous calls, also create a `Call` object but use the `enqueue` method.

[source,java]
----
client.newCall(request).enqueue(new Callback() {
    @Override
    public void onFailure(Call call, IOException e) {
        e.printStackTrace();
    }

    @Override
    public void onResponse(Call call, final Response response) throws IOException {
        if (!response.isSuccessful()) {
            throw new IOException("Unexpected code " + response);
        } else {
        // do something wih the result
    }
}
----

Note: If you are using Android and want to update the UI, you need to use `Content.runOnUiThread(new Runnable)` to sync with the UI thread.
