[[ottoeventbus]]
== Otto as event bus system 

[[ottoeventbus_intro]]
=== Otto as event bus system 
(((Otto)))
(((Event bus)))
http://square.github.io/otto/[Otto] is an open source project providing an event bus implementation.
Components can publish and subscribe to events.
		
Otto has been a fork of the _Guava_ event bus library from Google and been redesigned to support Android as well as possible. 
Unlike the Guava event bus, Otto does not consider event subscriptions from base classes or interface.
This is done to improve performance of the library and to keep the application code simple and unambiguous.
		
[[ottoeventbus_installation]]
=== Installation
		
		
If you are using Maven or Gradle as build system you can simply add a
dependency to it.

[source,gradle]
----
dependencies {
  compile 'com.squareup:otto:1.3.8'
}
----

[source, xml]
----
<dependency>
  <groupId>com.squareup</groupId>
  <artifactId>otto</artifactId>
  <version>1.3.8</version>
</dependency>
----

You could also download the JAR manually from http://square.github.io/otto/[Download Otto] and add it to the classpath of your application.

[[ottoeventbus_whenouse]]
=== When to use Otto?

Otto can be used to communicate between your activity and fragments or to communicate between an activity and a service.

[NOTE]
====
An alternative solution would be the usage of http://www.vogella.com/tutorials/RxJava/article.html[RxJava].
See http://blog.kaush.co/2014/12/24/implementing-an-event-bus-with-rxjava-rxbus/[Implementing an Event Bus With RxJava blog post] for an example.
====

[[ottoeventbus_howtosetup]]
=== How to setup Otto?

NOTE: The following description assumes your are using Otto in an
Android application, even though it is possible to use it in an standard Java application.
		
To use Otto, create a singleton instance of the `Bus` class and provide access to it for your Android components.
This is typically done in the `Application` object of your Android application.

[source,java]
----
include::res/snippets/CreateBus.java[]
----
		
In this example the `ThreadEnforcer.MAIN` parameter is used,.
This enforces Otto to send events always from the main thread.
If you want to be able to send events from any thread use the `ThreadEnforcer.ANY` parameter.

=== How to register and unregister for events?

(((@Subcribe)))
(((Otto,@Subcribe)))
Event registration is done via the `@Subcribe` annotation on a public single parameter method. 
The method parameter is the event key, i.e., if such an data type is send via the Otto event bus the method is called.
		
Event receivers must register via the `register` method of the `Bus` class.

[source,java]
----
include::res/snippets/Register.java[]
----
		
To unregister from events use the `unregister()` method.

=== How to send events

For sending events it is not necessary to register with the event bus. 
Simple call the `post()  method of the `Bus` class.

[source,java]
----
include::res/snippets/Send.java[]
----

[[ottoeventbus_newcomponent]]
=== How can new components receive the last event?

(((@Produce)))
(((Otto,@Produce)))
Sometimes new components, like a dynamically created fragment, should receive event data during their creation.
If this case component can register as producer for such event data with the `@Produce` annotation.
		
Event receivers must register via the `register` method of the `Bus` class.

[source,java]
----
include::res/snippets/Produce.java[]
----

