[[customannotations_defineanduse]]
== Defining custom annotations

[[customannotations_definition]]
=== Define your custom annotation

The Java programming language allows you to define your custom annotations.
Annotations are defined via the `@interface` annotation before the class name. 
Via `@Retention` you define if the annotation should be retained at runtime or not.
The `@Target` annotation lets you define where this annotation can be used, e.g., the class, fields, methods, etc.

A typical annotation definition would look like the following.

[source, java]
----
include::examples/OwnAnnotation.java[]
----

You can add additional information, for example you can define that your annotation is a qualifier for the `@Inject`annotation.


[source, java]
----
include::examples/Checker.java[]
----



[[customannotations_usage]]
=== Accessing your annotation via Java reflection

To process your annotation you could write your own annotation processor. 
Typically you use Java reflection for this. 
Java reflection allows you to analyze a Java class and use the information contained in this class at runtime.
