==	Exercise -  Using Hamcrest matchers

=== Target

The target of this exercise is to make use of Hamcrest matchers.

=== Using Hamcrest collection matchers for lists

==== Target

Assume the following code:

[source,java]
----
List<Integer> list = Arrays.asList(5, 2, 4);
----


. Ensure via tests with Hamcrest matchers that `list`:

* has a size of 3
* contains the elements 2, 4, 5 in any order
* every item is greater than 1


=== Solutions for collection matchers

[source, java]
----
include::res/exercise-matcher/sizeOf3.java[]
----

[source, java]
----
include::res/exercise-matcher/ElementsInAnyOrder.java[]
----

[source, java]
----
include::res/exercise-matcher/EveryItemGreaterThan1.java[]
----

=== Using Hamcrest collection matchers for arrays

==== Target

Assume the following code:

[source,java]
----
Integer[] ints = new Integer[] {7, 5, 12, 16};
----

. Ensure via tests with Hamcrest matchers that the `ints` array

* has a size of 4
* contains 7, 5 , 12 , 16 in the given order


==== Solution - Array Exercises

[source, java]
----
include::res/exercise-matcher/ArraySizeOf4.java[]
----

[source, java]
----
include::res/exercise-matcher/ArrayElementsInOrder.java[]
----

=== Using Hamcrest beans matchers

==== Target

Assume the following code:

[source,java]
----
class Todo {
        
    private final long id;
    private String summary;
    private String description;
    private int year;

    public Todo(long id, String summary, String description) {
        this.id = id;
        this.summary = summary;
        this.description = description;
    }

    // getters/setters
}
----

Write tests that ensure that:

* Todo has a property called "summary"
* If Todo is constructed with the summary "Learn Hamcrest" that the summary property has
the correct value
* Two objects created with the same values, have the same property values


==== Solution

[source,java]
----
@Test
public void objectHasSummaryProperty () {
    
    Todo todo = new Todo(1, "Learn Hamcrest", "Important");
    
    assertThat(todo, hasProperty("summary"));
}  
----

[source,java]
----
@Test
public void objectHasSummaryProperty () {
    
    Todo todo = new Todo(1, "Learn Hamcrest", "Important");
    
    assertThat(todo, hasProperty("summary"));
}  
----

[source,java]
----
@Test
public void objectHasCorrectSummaryValue () {
    
    Todo todo = new Todo(1, "Learn Hamcrest", "Important");
    
    assertThat(todo, hasProperty("summary", equalTo("Learn Hamcrest")));
}  
----

[source,java]
----
@Test
public void objectHasSameProperties () {
    
    Todo todo1 = new Todo(1, "Learn Hamcrest", "Important");
    Todo todo2 = new Todo(1, "Learn Hamcrest", "Important");
    
    assertThat(todo1, samePropertyValuesAs(todo2));
}  
----

=== Using Hamcrest String matchers

==== Target

Write tests that ensure that:

* "" is an empty string
* a given string is either empty or null

==== Solution
[source,java]
----
import org.junit.Test;

import static org.junit.Assert.*;
import static org.hamcrest.text.IsEmptyString.isEmptyString;
import static org.hamcrest.text.IsEmptyString.isEmptyOrNullString;

public class StringMatcherTest {
    @Test
    public void isStringEmpty() {
        String stringToTest = "";
        assertThat(stringToTest, isEmptyString());
    }

    @Test
    public void isStringEmptyOfNull() {
        String stringToTest = "";
        assertThat(stringToTest, isEmptyOrNullString());
    }

}
----

