==	Exercise - Writing a custom Hamcrest matcher using FeatureMatcher

=== Target

The target of this exercise is to write a custom matcher with Hamcrest.

=== Create Hamcrest Matchers

Define a custom matcher for Hamcrest which provides the `length` matcher for a String.
We want to use the class `FeatureMatcher`.
With FeatureMatcher we can wrap an existing Matcher, decide which field of the given Object under test to match
and provide a nice error message.
The constructor of FeatureMatcher takes the following arguments in this order:

* The matcher we want to wrap
* a description of the feature that we tested
* a description of the possible mismatch

The only method we have to overwrite is `featureValueOf(T actual)` which returns the value which will get passed into the wrapped `matches()`/`matchesSafely()` method.

[source,java]
----
public static Matcher<String> length(Matcher<? super Integer> matcher) {
    return new FeatureMatcher<String, Integer>(matcher, "a String of length that", "length") {
        @Override
        protected Integer featureValueOf(String actual) {
            return actual.length();
        }
    };
}
----

=== Validate

Use your custom matcher to check that "Gandalf" has a lenght of 8.

[source,java]
----
@Test
public void fellowShipOfTheRingShouldContainer7() {
	assertThat("Gandalf", length(is(8)));
}
public static  Matcher<String> length(Matcher<? super Integer> matcher) {
	return new FeatureMatcher<String, Integer>(matcher, "a String of length that", "length") {
		@Override
		protected Integer featureValueOf(String actual) {
		  return actual.length();
		}
	};
}
----

