[[hamcrest_extending]]
==	Exercise: Writing your custom Hamcrest matcher using TypeSafeMatcher

It is possible to write your custom Hamcrest matcher by extending TypeSafeMatcher. 
In contrast to BaseMatcher the TypeSafeMatcher class automatically checks for `null` values, checks the type and casts appropriately before delegating to `matchesSafely()`.
It provides type safety by default.
The following is an example for defining a matcher which allows testing if a String matches a regular expression.
	
[source, java]
----
import org.hamcrest.Description;
import org.hamcrest.TypeSafeMatcher;

public class RegexMatcher extends TypeSafeMatcher<String> {

	private final String regex;

	public RegexMatcher(final String regex) {
		this.regex = regex;
	}

	@Override
	public void describeTo(final Description description) {
		description.appendText("matches regular expression=`" + regex + "`");
	}

	@Override
	public boolean matchesSafely(final String string) {
		return string.matches(regex);
	}
	

	 // matcher method you can call on this matcher class
    public static RegexMatcher matchesRegex(final String regex) {
        return new RegexMatcher(regex);
    }
}
----	
	
The following snippet gives an example how to use it. 

[source, java]
----
package com.vogella.android.testing.applicationtest;


import org.junit.Test;

import static org.hamcrest.MatcherAssert.assertThat;

public class TestCustomMatcher {

    @Test
    public void testRegularExpressionMatcher() throws Exception {
        String s ="aaabbbaaaa";
        assertThat(s, RegexMatcher.matchesRegex("a*b*a*"));
    }

}
----	

== Grouping your matchers for import

If you define many custom matchers it might become tedious to import them one by one into your test files.
By grouping them into a single class you can import them with one statement.
You can also group them together with Hamcrest matchers.

[source, java]
----
package com.vogella.hamcrest;
import com.vogella.hamcrest.matchers.RegexMatcher;
import org.hamcrest.Matcher;
import org.hamcrest.Matchers;

public class MyMatchers
{
    public static <T> Matcher<T> instanceOf(Class<T> target) {
        return Matchers.instanceOf(target);
    }
   
   public static Matcher<String> matchesRegex(String target) {
          return RegexMatcher.matchesRegex(target);
   }
}
----

In your test file:

[source, java]
----
import static com.vogella.hamcrest.MyMatchers.*;
----
	
