== RxJava

=== What is RxJava and reactive programming

In reactive programming the consumer reacts to the data as it comes in, which is why asynchronous programming is also called reactive programming.
Reactive programming allows to propagates event changes to registered observers.
RxJava is a port from Netflix of the Reactive Extensions (Rx) to Java.
RxJava was open sourced 2014 and is hosted at http://reactivex.io/.
The Java version of this concept is called RxJava and is hosted under https://github.com/ReactiveX/RxJava.
RxJava is published under the Apache 2.0 license.

RxJava describes itself as an API for asynchronous programming with observable streams

=== Define a dependency to RxJava

As of this writing the version 1.1.3 is currently the released one. 
Replace x.y.z with 1.1.3 or a later version.

For Maven you can add a dependency with the following snippet

[source, xml]
----
<dependency>
    <groupId>io.reactivex</groupId>
    <artifactId>rxjava</artifactId>
    <version>x.y.z</version>
</dependency>
----

For Gradle you can add it RxJava via the following dependency closure.

[source, xml]
----
<dependency org="io.reactivex" name="rxjava" rev="x.y.z" />
----

=== How does RxJava work?

RxJava provides Observables and Observers.
Observables can send out values. 
Observers, watch Observables by subscribing to them.
Observers are notified when an Observable emits a value, when the Observable says an error has occurred. 
They are also notified when the	Observable sends the information that it no longer has any values to emit. 
The corresponding functions are `onNext`, `onError`, and `onCompleted()` encapsulated in the Observer interface.

RxJava provides several methods to create an observable.
`Observable.just()` creates an Observable such that when an Observer subscribes, the `onNext()` 
of the Observer is immediately called with the argument provided to `Observable.just()`.


