== RxJava 2.0

=== What is RxJava and reactive programming

In reactive programming the consumer reacts to the data as it comes in.
This is the reason why asynchronous programming is also called reactive programming.
Reactive programming allows to propagates event changes to registered observers.

RxJava is a port from Netflix of the Reactive Extensions (Rx) to Java.
RxJava was open sourced 2014 and is hosted at http://reactivex.io/.
The Java version of this concept is called RxJava and is hosted under https://github.com/ReactiveX/RxJava.
RxJava is published under the Apache 2.0 license.

RxJava describes itself as an API for asynchronous programming with observable streams

=== Define a dependency to RxJava 2.0

As of this writing the version 2.0.1 is currently the released one. 
Replace g.a.v with 2.0.1 or a later version.

For Maven you can add a dependency with the following snippet

[source,xml]
----
<dependency>
    <groupId>io.reactivex.rxjava2</groupId>
    <artifactId>rxjava</artifactId>
    <version>g.a.v</version>
</dependency>
----

For a Gradle build you can add RxJava via the following dependency statement.

[source, groovy]
----
compile group: 'io.reactivex.rxjava2', name: 'rxjava', version: 'g.a.v'
----

=== Async programming

Nowadays programming in an imperative single threaded way usually leads to strange behaviors, blocking non responsive UIs and therefore a bad user experience.

This can be avoided by handling unpredicted things asynchronously. For example actively waiting for a database query or a webservice call can cause an application freeze, if the network is not responsive.

An example would be:

[source, java]
----
public List<Todo> getTodos() {
	
	List<Todo> todosFromWeb = // query a webservice (with bad network latency)
	
	return todosFromDb;
}
----

Calling the getTodos() method from the main thread or an UI thread will cause a non responsive application until the `todosFromWeb` arrive.

icon:thumbs-o-down[]

To improve this the query, which takes an unpredictable amount of time, should run in a different thread and inform the main thread when a result comes in.

[source, java]
----
public void getTodos(Consumer<List<Todo>> todosConsumer) {

	Thread thread = new Thread(()-> {
		List<Todo> todosFromWeb = // query a webservice

		todosConsumer.accept(todosFromWeb);
	});
	thread.start();
}
----

Now after calling the `getTodos(Consumer<List<Todo>> todosConsumer)` the main thread can continue working, is not blocked and can react once the accept method of the given `Consumer` is called.

icon:thumbs-o-up[]

=== Observables, Observers and Subscriptions

RxJava provides _Observables_ and _Observers_.
Observables can send out values. 
Observers, watch Observables by subscribing to them.
Observers are notUsingified when an Observable emits a value, when the Observable says an error has occurred. 
They are also notified when the	Observable sends the information that it no longer has any values to emit. 
The corresponding functions are `onNext`, `onError`, and `onCompleted()` from the `Observer` interface.
A instance of `Subscription` represents the connection between an observer and an observable. 
In you call `unsubscribe()` on this instance to remove the connection. 
This is for example useful to avoid updates to widgets after they have been disposed.
 
=== Defining the execution thread and the thread for observing

You can specify the thread in with the observable is executed via the `subscribeOn()` method. 
The thread in which the observers are executed can be defined via the `observeOn()` method.

== Operators

You can register operations on your observers which allows you to manipulate the emission of an observable before passing it to the  observer. 
For example the `map` method allows to register a `Func1` which translates the input.


== Using delays

Via the `debounce(delay, TimeUnit.MILLISECONDS)` method on the observer, you can instruct it to only emit the changes if the value has not changed for a predefined delay. 

