== RxJava Observable Types

[quote, reactivex.io]
____
The Observer pattern done right.
ReactiveX is a combination of the best ideas from the Observer pattern, the Iterator pattern, and functional programming.
____

In order to archive this RxJava comes with *observable types* acting as the sources of data, *classes to subscribe* to these observable types and a lot of methods for *modifying, composing and transforming the data* being exchanged between the observable and the subscriber.

Some of the methods are pretty similar to the ones Java 8 provides with the `Stream` API, e.g., `filter()`, `map()` and so on.


.Table Obervable types
|===
|Type

|Flowable<T>

|Observable<T>

|Single<T>

|Maybe<T>

|Completable

|===

Types that can emit data infinite are `Flowable<T>` and `Obervable<T>`.

[source, java]
----
Observable<Todo> todoObservable = Observable.create(emitter -> {
	try {
		List<Todo> todos = getTodos();
		for (Todo todo : todos) {
			emitter.onNext(todo);
		}
		emitter.onComplete();
	} catch (Exception e) {
		emitter.onError(e);
	}
});
----

Typical Observable that could emit likely infinite data are UI listener like a click listener, where it is unpredictable that often a user might click on a button or other UI widget.

Types that usually terminate either successfully or on failure are `Maybe<T>`, `Single<T>` and `Completable`.

`Maybe<T>` objects are kind of an async `java.util.Optional` from Java 8.

[source, java]
----
Maybe<List<Todo>> todoMaybe = Maybe.create(emitter -> {
	try {
		List<Todo> todos = getTodos();
		if(todos != null && !todos.isEmpty()) {
			emitter.onSuccess(todos); #<1>
		}else {
			emitter.onComplete(); #<2>
		}
	} catch (Exception e) {
		emitter.onError(e); #<3>
	}
});
----

<1> `java.util.Optional` has a value
<2> `java.util.Optional` contains no value -> null
<3> An error occurred

`Single<T>` objects can also be considered as promises, which are also pretty popular in async frameworks and are similar to `Maybe<T>` objects, but only without the `onComplete()` method.

`Completable` objects are pretty similar to `Single<T>` objects, but without return value and therefore also do not have a generic type `<T>` like the other types.

Besides the most popular `create()` method of these observable type there are more convenience methods to create one of these types.

* Observable.just() - Allows to create an observable as wrapper around other data types
* Observable.fromIterable() - takes an `java.lang.Iterable<T>` and emits their values in their order in the data structure
* Observable.fromArray() - takes an array and emits their values in their order in the data structure
* Observable.fromCallable() - Allows to create an observable for a `java.util.concurrent.Callable<V>`
* Observable.fromFuture() - Allows to create an observable for a `java.util.concurrent.Future`
* Observable.interval() - An observable that emits `Long` objects in a given interval
* ...

