== Creating Observables and Observers

RxJava provides several methods to create an observable.

* Observable.just() - Allows to create an observable as wrapper around other data types
* Observable.from() - takes a collection or an array and emits their values in their order in the data structure
* Observable.fromCallable() - Allows to create an observable for a Callable`

To create observers:

* Implement Action1 - Allow you to create a simple observer  which has a `call` methods.
This method is called if a new object is emitted.

=== Example for using Observable.just()

`Observable.just()` creates an Observable such that when an Observer subscribes, the `onNext()` 
of the Observer is immediately called with the argument provided to `Observable.just()`.


[source, java]
----
import java.util.Arrays;
import java.util.List;

import rx.Observable;

public class RxJavaExample {
	public static void main(String[] args) {
		List<String> list = Arrays.asList("Android", "Ubuntu", "Mac OS"); #<1>
		Observable<List<String>> listObservable = Observable.just(list);  #<2>
		listObservable.subscribe(new Observer<List<String>>() {			  #<3>

            @Override
            public void onCompleted() {}

            @Override
            public void onError(Throwable e) {}

            @Override
            public void onNext(List<String> list) {
				System.out.println(list);
            }
        });
	}
}
----

<1> Creates a list
<2> Creates the Observable
<3> Registers the Observer

== Performing conversions

The following is a simple example of RxJava in which some conversion is performed.

[source, java]
----
import java.util.Arrays;
import java.util.List;

import rx.Observable;

public class RxJavaExample {
	public static void main(String[] args) {
		List<String> list = Arrays.asList("Hello", "Streams", "Not");
		Observable.from(list).
				filter(s -> s.contains("e")).
				map(s -> s.toUpperCase()).
				reduce(new StringBuilder(), StringBuilder::append).
				subscribe(System.out::print, e -> {}, 
				() -> System.out.println("!"));
	}
}
----

=== Single 

Instances of  `Single` work similar to `Observable` but they have only two callbacks `onSuccess()` and `onError()`.
To subscribe to a `Single` use the `SingleSubscriber` interface.

=== Subjects

Subjects are objects that are both an Observable and an Observer. 
Subjects can be used as a pipe to translate data. 
An example for a subject is a `PublishSubject`.
As soon as something is send to a PublishSubject it is immediately send out again.

