== Exercise: First steps with RxJava and RxAndroid

Create a new project with the `com.vogella.android.rxjava.simple` top level package name.

=== Gradle dependencies

Add the following dependencies to your app/build.gradle file.

[source,gradle]
----
compile 'com.android.support:recyclerview-v7:23.1.1'
compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
compile 'io.reactivex.rxjava2:rxjava:2.0.8'
compile 'com.squareup.okhttp:okhttp:2.5.0'
testCompile 'junit:junit:4.12'
----
Also enable the usage of Java 8 in your app/build.gradle file.

[source,gradle]
----
android {
   // more stuff
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
----

=== Create activities

Change your main layout file to the following.

[source,xml]
----
include::./res/android/activity_main.xml[]
----

Create three activities:

* RxJavaSimpleActivity
* BooksActivity
* ColorsActivity

Create the activity_rxjavasimple.xml layout file.

[source,xml]
----
include::./res/android/activity_rxjavasimple.xml[]
----

activity_colors.xml


In `RxJavaSimpleActivity` create a observable which simulates a long running operation (10 secs) and afterwards returns the number 5.
Subscribe to it via a button click, disable the button

[source,java]
----
include::./res/android/RxJavaSimpleActivity.java[]
----


Create an adapter for a recycler view.

[source,java]
----
include::./res/android/SimpleStringAdapter.java[]
----

Implement  `ColorsActivity` which uses a observable to receive a list of colors.


Create the activity_colors.xml layout file.

[source,xml]
----
include::./res/android/activity_colors.xml[]
----


[source,java]
----
include::./res/android/ColorsActivity.java[]
----

Create the following (fake) server implementation.

[source,java]
----
include::./res/android/RestClient.java[]
----

Create the activity_books.xml layout file.

[source,xml]
----
include::./res/android/activity_books.xml[]
----

Also implement the `BooksActivity` activity.

[source,java]
----
include::./res/android/BooksActivity.java[]
----




