[[mockitousage]]
== Using the Mockito API

=== Static imports

If you add a static import for `org.mockito.Mockito.*;`, you can access Mockitos methods like `mock()` directly. 
Static imports allows you to call static members, i.e., methods and fields of a class directly without specifying the class.
		
=== Creating and configuring mock objects with Mockito

Mockito supports the creation of mock objects. 
For this you can use the static `mock()` method.

Mockito also supports the creation of mock objects based on the `@Mock` annotation.
        
If you use this annotation, you must initialize the mock objects. 
The `MockitoRule` allows this. 
It invokes the static method `MockitoAnnotations.initMocks(this)` to populate the annotated fields. 
Alternatively you can use `@RunWith(MockitoJUnitRunner.class)`.

The usage of the `@Mock` annotation and the `MockitoRule` rule is demonstrated by the following example.

[source,java]
----
include::res/simple/TestSimple.txt[]
----   

<1> Tells Mockito to mock the databaseMock instance
<2> Tells Mockito to create the mocks based on the @Mock annotation
<3> Instantiates the class under test using the created mock
<4> Executes some code of the class under test
<5> Asserts that the method call returned true
<6> Verify that the query method was called on the `MyDatabase` mock

=== Configuring mocks

To configure which values are returned at a method call the Mockito framework defines a fluent API. 
		
The `when(....).thenReturn(....)` method chain is be used to specify a condition and a return value for this condition. 
If you specify more than one value,	they are returned in the order of specification until the last one is used. 
Afterwards the last	specified value	is returned. 
Mocks can also return different values depending on arguments passed into a method. 
You also use methods like `anyString` or `anyInt` to define that independent of the input value a certain return value should be returned.

[source,java]
----
include::res/api/WhenThenReturn.java[]
----

		
The `doReturn(...).when(...).methodCall` call chain works similar but is useful for void methods. 
The `doThrow` variant can be used for methods which return `void` to throw an exception. 
This usage is demonstrated by the following code snippet.
		

[source,java]
----
include::res/api/doReturnWhen.java[]
----		




[[mockito_verify]]
===	Verify the calls on the mock objects
		
Mockito keeps track of all the method calls and their parameters to the mock object. 
You can use the `verify()` method on the mock object to verify that the specified conditions are met
For example, you can verify that a method has been called with certain parameters.
This kind of testing is sometimes called _behavior testing_. 
Behavior testing does not check the result of a method call, but it checks that a method is called with the right parameters.
		
[source,java]
----
include::res/api/Verify.java[]
----
		

[[mockito_spy]]
=== Wrapping Java objects with Spy
		
@Spy or the `spy()` 	method can be used to wrap a real object. 
Every call, unless specified otherwise, is delegated to the object.
		
[source,java]
----
include::res/simple/Spy.txt[]
----		
		
The `verifyNoMoreInteractions()` allows you to check that no other method was called.
		
[[mockito_dependencyinjection]]
=== Using @InjectMocks for dependency injection via Mockito
		
You also have the `@InjectMocks` annotation which tries to do constructor, method or field dependency injection based on the type. 
For example, assume that you have the following class.
		
[source,java]
----
public class ArticleManager {
    private User user;
    private ArticleDatabase database;
    
    ArticleManager(User user) {
     this.user = user;
    }

    void setDatabase(ArticleDatabase database) { }
}
    
----		

This class can be constructed via Mockito and its dependencies can be fulfullied with mock objects as demonstrated by the following code snippet.		
[source,java]
----
include::res/snippet/Example.java[]
----		

<1> creates an instance of ArticleManager and injects the mocks into it

=== Capturing the arguments

The `ArgumentCaptor` class allows to access the arguments of method calls during the verification.
This allows to capture these arguments of method calls and to use them for tests.

[source,java]
----
import static org.hamcrest.Matchers.hasItem;
import static org.junit.Assert.assertThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;

import java.util.Arrays;
import java.util.List;

import org.junit.Rule;
import org.junit.Test;
import org.mockito.ArgumentCaptor;
import org.mockito.Captor;
import org.mockito.junit.MockitoJUnit;
import org.mockito.junit.MockitoRule;


public class MockitoTests {
    
	@Rule public MockitoRule rule = MockitoJUnit.rule();

	@Captor
    private ArgumentCaptor<List<String>> captor;
	
			
	@Test
    public final void shouldContainCertainListItem() {
		List<String> asList = Arrays.asList("someElement_test", "someElement");
        final List<String> mockedList = mock(List.class);
        mockedList.addAll(asList);
        
        verify(mockedList).addAll(captor.capture());
        final List<String> capturedArgument = captor.<List<String>>getValue();
        assertThat(capturedArgument, hasItem("someElement"));
    }
}
----        

      
		
[[mockito_limitations]]
=== Limitations
		
Mockito has certain limitations. 
It can not test the following constructs:

* final classes
* anonymous classes
* primitive types


