== Decorating EventLists to extend the functionality

In GlazedLists the decorator design pattern is used a lot in order to add functionality to a given `EventList`.

=== Concurrency

Even though the `EventList` class provides a getter for `ReadWriteLock` it is not thread safe by default.

[source, java]
----
List<String> listOfNames = getListOfNames();
EventList<String> eventList = GlazedLists.eventList(listOfNames);
EventList<String> threadSafeEventList = GlazedLists.threadSafeList(eventList);
----

=== Sorting an EventList

To automatically sort an `EventList` it can be decorated into a `SortedList`.

[source, java]
----
EventList<? extends Comparable> basicEventList = new BasicEventList<>();
SortedList<? extends Comparable> sortedList = new SortedList<>(basicEventList);
----

[source, java]
----
List<String> listOfNames = getListOfNames();
EventList<String> eventList = GlazedLists.eventList(listOfNames);
// the second parameter is a java.util.Comparator<T>
SortedList<String> sortedList = new SortedList<>(eventList, (s, s2) -> s.compareTo(s2));
----


[NOTE]
====
You can also pass `null` as `java.util.Comparator<T>` and apply it later.

[source, java]
----
new SortedList<>(eventList, null);
----
====

=== Observing the properties of objects in an EventList

The `EventList` is able to fire events upon a change to the list itself.
So adding, removing and setting elements for the list instance can be tracked by using a plain `EventList`, but if also the properties of elements in the list should be tracked an `ObservableElementList` will be the right choice.

The `ObservableElementList` takes an `EventList` and a `ObservableElementList.Connector` as parameters. By implementing the `Connector` interface a possibility to track the elements in the list can be provided. +  
It has 3 methods:

[source, java]
----
public interface Connector<E> {
	public EventListener installListener(E element);

	public void uninstallListener(E element, EventListener listener);

	public void setObservableElementList(ObservableElementList<? extends E> list);
}
----

The `GlazedLists` class provides some methods to create default `Connector` instances like `GlazedLists.beanConnector(Person.class)` or `GlazedLists.observableConnector()`.

An `ObservableElementList` for `Person` objects could be created like this:

[source, java]
----
EventList<Person> personEventList = GlazedLists.eventList(persons);
ObservableElementList<Person> observableElementList =
	new ObservableElementList<>(personEventList, GlazedLists.beanConnector(Person.class));
----


