[[junittesting]]
== Using JUnit

[[unittesting_junit]]
=== The JUnit framework
(((JUnit framework)))
(((JUnit,@Test)))

_JUnit_ in version 4.x is a test framework which uses annotations to identify methods that specify a test.
The main websites for JUnit are the JUnit homepage (http://junit.org/) and the Github project page (https://github.com/junit-team/junit).

[[unittesting_junit_test]]
=== How to define a test in JUnit?
		
A JUnit _test_ is a method contained in a class which is only used for testing. 
This is called a _Test class_.
To write a JUnit 4 test you annotate a method with the `@org.junit.Test` annotation.
		
This method executes the code under test.		
You use an _assert_ method, provided by JUnit or another assert framework, to check an expected result versus the actual result. 
These method calls are typically called _asserts_ or _assert statements_.
		
You should provide meaningful messages in assert statements.
That makes it easier for the user to identify and fix the problem. 
This is especially true if someone looks at the problem, who did not write the code under test or the test code.

[[unittesting_junitexample]]
=== Example JUnit test
		
The following code shows a JUnit test. 
This test assumes that the `MyClass` class exists and has a `multiply(int, init)` method.
		
[source,java]
----
include::res/example/test.java[]
----

[[junit_namingconventions]]
=== JUnit naming conventions
(((Naming conventions for test methods)))

There are several potential naming conventions for JUnit tests.
A widely-used solution is to add the suffix "-test" to the names of the test classes and create them in a new package "test".

        
As a general rule, a test name should explain what the test does.
If that is done correctly, reading the actual implementation can be avoided.
	
One possible convention is to use the word "should" in the test method name.
For example, "ordersShouldBeCreated" or "menuShouldGetActive". 
This gives a hint what should happen if the test method is executed.

[[junit_namingconventions_maven]]
=== JUnit naming conventions for Maven

If you are using the Maven build system, you should prefer the "Test" suffix over "Tests".
The Maven build system (via its surfire plug-in) automatically includes such classes in its test scope.
		
[[juniteclipse_testsuite]]

=== JUnit test suites
(((JUnit,Test suite)))
		
If you have several test classes, you can combine them into a _test suite_ . 
Running a test suite executes all test classes in that suite in the specified order.
A test suite can also contain other test suites. 
		
The following example code demonstrates the usage of a test suite. 
It  contains two test classes (MyClassTest and MySecondClassTest).
If you want to add another test class, you can add it to the `@Suite.SuiteClasses` statement.
		
[source,java]
----
include::res/example/AllTests.java[]
----

[[juniteclipse_code]]

=== Run your test from the command line
		
You can also run your JUnit tests outside our IDE via standard Java code. 
Build systems like Apache Maven or Gradle in combination with a Continuous Integration Server (like Jenkins) can be used to execute tests automatically on a regular basis.
		
The `org.junit.runner.JUnitCore` class provides the `runClasses()` method. 
This method allows you to run one or several tests classes. 
As a return parameter you receive an object of the type `org.junit.runner.Result`. 
This object can be used to retrieve information about the tests.
		
The following class demonstrates how to run the `MyClassTest`. 
This class executes your test class and write potential failures to the console.

[source,java]
----
include::res/code/MyTestRunner.java[]
----

This class can be executed like any other Java program on the command line. 
You only need to add the JUnit library JAR file to the classpath.
		
