[[junitannoationsandassertstatements]]
== Basic JUnit code constructs

[[usingjunit_annotations]]
=== Available JUnit annotations
(((JUnit,Annotations)))
(((Test annotations from JUnit)))

JUnit 4.x uses annotations to mark methods as test methods and to configure them.
The following table gives an overview of the most important annotations in JUnit.

.Annotations
[cols="1,2",options="header"]
|===
|Annotation |Description

|@Test + 
public void method()
|The `@Test` annotation identifies a method as a test method.

|@Test (expected = Exception.class)
|Fails if the method does not throw the named exception.

|@Test(timeout=100)
|Fails if the method takes longer than 100 milliseconds.

|@Before + 
public void method()
|This method is executed before each test. It is used to
prepare the test environment (e.g., read input
data, initialize the class).

|@After + 
public void method()
|This method is executed after each test. It is used to cleanup the test environment (e.g., delete temporary data, restore defaults). It can also save memory by cleaning up expensive memory structures.

|@BeforeClass + 
public static void method()
|This method is executed once, before the start of all tests.
It is used to perform time intensive activities, for example, to connect to a database. Methods marked with this annotation need to be defined as `static` to work with JUnit.

|@AfterClass + 
public static void method()

|This method is executed once, after all tests have been finished.
It is used to perform clean-up activities, for example, to disconnect from a database. Methods annotated with this annotation need to be defined as `static` to work with JUnit.

|@Ignore or @Ignore("Why disabled")
|Ignores the test method. This is useful when the
underlying code has been changed and the test case has not
yet
been
adapted. Or if the execution time of this test is too long
to be
included. It is best practice to provide
the optional
description, why the test is disabled.
|===

[[usingjunit_asserts]]
=== Assert statements
(((JUnit,Assert statements)))
		
JUnit provides static methods to test for certain conditions via the `Assert`class. 
These _assert statements_ typically start with `assert`.
They allow you to specify the error message, the expected and the actual result.
An _assertion method_ compares the actual value returned by  a test to the expected value.
It throws an `AssertionException` if the comparison fails.

The following table gives an overview of these methods.
Parameters in [] brackets are optional and of type String.

.Methods to assert test results
|===
|Statement | Description

|fail(message)
|Let the method fail. Might be used to check that a certain part of the code is not reached or to have a failing test before the test code is implemented.
The message parameter is optional.

|assertTrue([message,] boolean condition)
|Checks that the boolean condition is true.

|assertFalse([message,] boolean condition)
|Checks that the boolean condition is false.

|assertEquals([message,] expected, actual)
|Tests that two values are the same. Note: for arrays the reference is checked not the content of the arrays.

|assertEquals([message,] expected, actual, tolerance)
|Test that float or double values match. The tolerance is the number of decimals which must be the same.

|assertNull([message,] object)
|Checks that the object is null.

|assertNotNull([message,] object)
|Checks that the object is not null.

|assertSame([message,] expected, actual)
|Checks that both variables refer to the same object.

|assertNotSame([message,] expected, actual)
|Checks that both variables refer to different objects.
|===

[[usingjunit_executionorder]]
=== Test execution order
(((JUnit,Test execution order)))
		
JUnit assumes that all test methods can be executed in an arbitrary order. 
Well-written test code should not assume any order, i.e., tests should not depend on other tests.
		
As of JUnit 4.11 the default is to use a deterministic, but not predictable, order for the execution of the tests.
		
		
You can use an annotation to define that the test methods are sorted by method name, in lexicographic order.
To activate this feature, annotate your test class with the `@FixMethodOrder(MethodSorters.NAME_ASCENDING)` annotation. 
You can also explicitely set the default by using the `MethodSorters.DEFAULT` parameter in this annotation. 
You can also use `MethodSorters.JVM` which uses the JVM defaults, which may vary from run to run.
		
[[junit_disablingtests]]
=== Disabling tests

The @Ignore annotation allow to statically ignore a test.
Alternatively  you can use `Assume.assumeFalse` or `Assume.assumeTrue` to define a condition for the test.
`Assume.assumeFalse` marks the test as invalid, if its condition evaluates to true.
`Assume.assumeTrue` evaluates the test as invalid if its condition evaluates  to false. 
For example, the following disables a test on Linux:

[source,java]
----
`Assume.assumeFalse(System.getProperty("os.name").contains("Linux"));`
----
	
