[[usingjuni4]]
== Using JUnit 4

[[usingjunit_annotations]]
=== Defining test methods

(((JUnit,Annotations)))
(((Test annotations from JUnit)))
JUnit uses annotations to mark methods as test methods and to configure them.
The following table gives an overview of the most important annotations in JUnit for the 4.x and 5.x versions.
All these annotations can be used on methods.


.Annotations
[cols="2,4",options="header"]
|===
JUnit 4 |Description

|`import org.junit.*`
| Import statement for using the following annotations.

|`@Test`
|Identifies a method as a test method.

|`@Before` 
|Executed before each test. It is used to
prepare the test environment (e.g., read input
data, initialize the class).

|`@After`
|Executed after each test. It is used to cleanup the test environment (e.g., delete temporary data, restore defaults). It can also save memory by cleaning up expensive memory structures.

|`@BeforeClass`
|Executed once, before the start of all tests.
It is used to perform time intensive activities, for example, to connect to a database. Methods marked with this annotation need to be defined as `static` to work with JUnit.

|`@AfterClass`
|Executed once, after all tests have been finished.
It is used to perform clean-up activities, for example, to disconnect from a database. Methods annotated with this annotation need to be defined as `static` to work with JUnit.

|`@Ignore` or `@Ignore("Why disabled")`
|Marks that the test should be disabled. This is useful when the
underlying code has been changed and the test case has not
yet
been
adapted. Or if the execution time of this test is too long
to be
included. It is best practice to provide
the optional
description, why the test is disabled.

|`@Test (expected = Exception.class)`
|Fails if the method does not throw the named exception.

|`@Test(timeout=100)`
|Fails if the method takes longer than 100 milliseconds.

|===

[[usingjunit_asserts]]
=== Assert statements

(((JUnit,Assert statements)))
JUnit provides static methods to test for certain conditions via the `Assert` class. 
These _assert statements_ typically start with `assert`.
They allow you to specify the error message, the expected and the actual result.
An _assertion method_ compares the actual value returned by  a test to the expected value.
It throws an `AssertionException` if the comparison fails.

The following table gives an overview of these methods.
Parameters in [] brackets are optional and of type String.

.Methods to assert test results
|===
|Statement | Description

|fail(message)
|Let the method fail. Might be used to check that a certain part of the code is not reached or to have a failing test before the test code is implemented.
The message parameter is optional.

|assertTrue([message,] boolean condition)
|Checks that the boolean condition is true.

|assertFalse([message,] boolean condition)
|Checks that the boolean condition is false.

|assertEquals([message,] expected, actual)
|Tests that two values are the same. Note: for arrays the reference is checked not the content of the arrays.

|assertEquals([message,] expected, actual, tolerance)
|Test that float or double values match. The tolerance is the number of decimals which must be the same.

|assertNull([message,] object)
|Checks that the object is null.

|assertNotNull([message,] object)
|Checks that the object is not null.

|assertSame([message,] expected, actual)
|Checks that both variables refer to the same object.

|assertNotSame([message,] expected, actual)
|Checks that both variables refer to different objects.
|===

		
[[juniteclipse_testsuite]]
=== JUnit test suites

(((JUnit,Test suite)))		
If you have several test classes, you can combine them into a test suite.
Running a test suite executes all test classes in that suite in the specified order.
A test suite can also contain other test suites. 
		
The following example code demonstrates the usage of a test suite. 
It  contains two test classes (MyClassTest and MySecondClassTest).
If you want to add another test class, you can add it to the `@Suite.SuiteClasses` statement.
		
[source,java]
----
include::res/example/AllTests.java[]
----

[[usingjunit_executionorder]]
=== Test execution order
(((JUnit,Test execution order)))
JUnit assumes that all test methods can be executed in an arbitrary order. 
Well-written test code should not assume any order, i.e., tests should not depend on other tests.
		
As of JUnit 4.11 the default is to use a deterministic, but not predictable, order for the execution of the tests.
		
		
You can use an annotation to define that the test methods are sorted by method name, in lexicographic order.
To activate this feature, annotate your test class with the `@FixMethodOrder(MethodSorters.NAME_ASCENDING)` annotation. 
You can also explicitely set the default by using the `MethodSorters.DEFAULT` parameter in this annotation. 
You can also use `MethodSorters.JVM` which uses the JVM defaults, which may vary from run to run.
		
[[junit_disablingtests]]
=== Disabling tests

The @Ignore annotation allow to statically ignore a test.
Alternatively  you can use `Assume.assumeFalse` or `Assume.assumeTrue` to define a condition for the test.
`Assume.assumeFalse` marks the test as invalid, if its condition evaluates to true.
`Assume.assumeTrue` evaluates the test as invalid if its condition evaluates  to false. 
For example, the following disables a test on Linux:

[source,java]
----
Assume.assumeFalse(System.getProperty("os.name").contains("Linux"));
----
	
[[junitadvanced]]
== Advanced JUnit 4 options

=== Parameterized test
(((JUnit,Parameterized test)))
JUnit allows you to use parameters in a tests class. 
This class can contain one test method and this method is executed with the different parameters provided.
		
You mark a test class as a parameterized test with the `@RunWith(Parameterized.class)` annotation.
		
Such a test class must contain a static method annotated with the `@Parameters` annotation.
That method generates and returns a collection of arrays. 
Each item in this collection is used as parameter for the test method.
		
You can use the `@Parameter` annotation on public fields to get the test values injected in the test.
		
The following code shows an example for a parameterized test. 
It tests the `multiply()` method of the `MyClass` class which is included as inner class for the purpose of this example.

[source,java]
----
include::res/parameter/ParameterizedTestFields.java[]
----

Alternatively to using the `@Parameter` annotation you can use a constructor in which you store the values for each test. 
The number of elements in each array
provided by
the
method annotated with
`@Parameters`
must
correspond to the number of parameters in the
constructor of the
class.
The class is created for each parameter and
the test
values are
passed
via the constructor to the class.

[source, java]
----
include::res/parameter/ParameterizedTestUsingConstructor.java[]
----

If you run this test class, the test method is executed with each defined parameter. 
In the above example the test method is executed three times.

A more flexible and easier to write approach is provided by the JUnitParams from https://github.com/Pragmatists/JUnitParams.

[[junitadvanced_rules]]
=== JUnit Rules
(((JUnit,Rules)))
Via JUnit rules you can add behavior to each tests in a test class.		
You can annotate fields of type `TestRule` with the `@Rule` annotation.
You can create objects which can be used and configured in your test methods. 
This adds more flexibility to your tests. 
You could, for example, specify which exception message you expect during the execution of your test code.
		
[source,java]
----
package de.vogella.junit.first;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class RuleExceptionTesterExample {

  @Rule
  public ExpectedException exception = ExpectedException.none();

  @Test
  public void throwsIllegalArgumentExceptionIfIconIsNull() {
    exception.expect(IllegalArgumentException.class);
    exception.expectMessage("Negative value not allowed");
    ClassToBeTested t = new ClassToBeTested();
    t.methodToBeTest(-1);
  }
}
----

JUnit already provides several useful rule implementations. 
For example, the `TemporaryFolder` class allows to setup files and folders which are automatically removed after each test run.

The following code shows an example for the usage of the `TemporaryFolder` implementation.

[source,java]
----
package de.vogella.junit.first;

import static org.junit.Assert.assertTrue;

import java.io.File;
import java.io.IOException;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

public class RuleTester {

  @Rule
  public TemporaryFolder folder = new TemporaryFolder();

  @Test
  public void testUsingTempFolder() throws IOException {
    File createdFolder = folder.newFolder("newfolder");
    File createdFile = folder.newFile("myfilefile.txt");
    assertTrue(createdFile.exists());
  }
}

----

For more examples of existing rules see https://github.com/junit-team/junit4/wiki/Rules.

=== Writing custom JUnit rules

To write your custom rule, you need to implement the `TestRule` interface. 
This interface defines the `apply(Statement, Description)` method which must return an instance of `Statement`.
Statement represent the tests within the JUnit runtime and Statement#evaluate() run these. 
Description describes the individual test. 
It allows to read information about the test via reflection.

The following is a simple example for adding a log statement to an Android application before and after test execution.

[source,java]
----
include::res/rule/MyCustomRule.java[]
----

To use this rule, simple add a field annotated with `@Rule` to your test class.

[source,java]
----
include::res/rule/UseCustomRule.java[]
----

[[junitadvanced_categories]]
=== Categories
(((JUnit,Categories)))
It is possible to define categories of tests and include or exclude them based on annotations. 
The following example is based on the https://github.com/junit-team/junit/blob/master/doc/ReleaseNotes4.8.md[JUnit 4.8 release notes].

[source,java]
----
include::res/categories/CategoriesExample.java[]
----

	