[[junitadvanced]]
== Advanced JUnit options

=== Parameterized test
(((JUnit,Parameterized test)))
		
JUnit allows you to use parameters in a tests class. 
This class can contain one test method and this method is executed with the different parameters provided.
		
		
You mark a test class as a parameterized test with the `@RunWith(Parameterized.class)` annotation.
		
Such a test class must contain a static method annotated with the `@Parameters` annotation.
That method generates and returns a collection of arrays. 
Each item in this collection is used as parameter for the test method.
		
You can use the `@Parameter` annotation on public fields to get the test values injected in the test.
		
The following code shows an example for a parameterized test. 
It tests the `multiply()` method of the `MyClass` class which is included as inner class for the purpose of this example.

[source,java]
----
include::res/parameter/ParameterizedTestFields.java[]
----		
		
		
Alternatively to using the `@Parameter` annotation you can use a constructor in which you store the values for each test. 
The number of elements in each array
provided by
the
method annotated with
`@Parameters`
must
correspond to the number of parameters in the
constructor of the
class.
The class is created for each parameter and
the test
values are
passed
via the constructor to the class.
		

		
<programlisting language="java">
	<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" parse="text"
		href="./examples/parameter/ParameterizedTestUsingConstructor.java" />
</programlisting>
		
		
If you run this test class, the test method is executed
with
each
defined
parameter. In the above example the test
method is executed
three times.

[[junitadvanced_rules]]
=== JUnit Rules
(((JUnit,Rules)))
		
Via JUnit rules you can add behavior to each tests in a test class.		
You can annotate fields of type `TestRule` with the `@Rule` annotation.
 you can create objects which can be used and configured in your test methods. 
This adds more flexibility to your tests. 
You could, for example, specify which exception message you expect during the execution of your test code.
		
[source,java]
----
include::res/rule/RuleExceptionTesterExample.java[]
----    
		
JUnit already provides several useful rule implementations. 
For example, the `TemporaryFolder` class allows to setup files and folders which are automatically removed after each test run.
		
The following code shows an example for the usage of the `TemporaryFolder` implementation.

[source,java]
----
include::res/rule/RuleTester.java[]
---- 		
		
For more examples of existing rules see
<ulink url="https://github.com/junit-team/junit/wiki/Rules">JUnit Rules wiki</ulink>
.
=== Writing custom JUnit rules
		
To write your custom rule, you need to implement the `TestRule` interface. 
This interface defines the `apply(Statement, Description)` method which must return an instance of `Statement`.
Statement represent the tests within the JUnit runtime and Statement#evaluate() run these. 
Description describes the individual test. 
It allows to read information about the test via reflection.
		
The following is a simple example for adding a log statement to an Android application before and after test execution.
		
[source,java]
----
include::res/rule/MyCustomRule.java[]
----    
		
		
To use this rule, simple add a field annotated with `@Rule` to your test class.
		
[source,java]
----
include::res/rule/UseCustomRule.java[]
---- 

[[junitadvanced_categories]]
=== Categories
(((JUnit,Categories)))
		
It is possible to define categories of tests and include or exclude them based on annotations. 
The following example is based on the
<ulink url="https://github.com/junit-team/junit/blob/master/doc/ReleaseNotes4.8.md">JUnit 4.8 release notes</ulink>
.

[source,java]
----
include::res/categories/CategoriesExample.java[]
---- 
	


