== Threads pools with the Executor Framework
	
TIP: You find this examples in the source section in Java project called
_de.vogella.concurrency.threadpools_.
	
Thread pools manage a pool of worker threads. The thread pools
contains a work queue which holds tasks waiting to get executed.
	
A thread pool can be described as a collection of
`Runnable`
objects

(work queue) and a connections of running threads. These
threads are
constantly running and are checking the work query for new
work. If
there is new work to be done they execute this Runnable. The
Thread
class itself provides a method, e.g. execute(Runnable r) to add
a new
`Runnable`
object to the work queue.
	
The Executor framework provides example implementation of the
java.util.concurrent.Executor interface, e.g.
Executors.newFixedThreadPool(int n) which will create n worker
threads. The ExecutorService adds life cycle methods to the Executor,
which allows to shutdown the Executor and to wait for termination.
	
TIP: If you want to use one thread pool with one thread which executes several runnables you can use the `Executors.newSingleThreadExecutor()` method.
	
Create again the Runnable.
	
[source,java]
----
include::res/threadpools/MyRunnable.java[]
----
	
Now you run your runnables with the executor framework.
	
[source,java]
----
include::res/threadpools/Main.java[]
----	
	
In case the threads should return some value (result-bearing threads) then you can use the `java.util.concurrent.Callable` class.
	
