== CompletableFuture
	
Asynchronous task handling is important for any application which performs time consuming activities, as IO operations.
Two basic approaches to asynchronous task handling are available to a Java application: 

* application logic blocks until a task completes
* application logic is called once the task completes, this is called a nonblocking approach.
	
`CompletableFuture` extends the functionality of the `Future` interface for asynchronous calls.
It also implements the `CompletionStage` interface.
`CompletionStage` offers  methods, that let you attach callbacks that will be executed on completion.


It adds standard techniques for executing application code when a task completes, including various ways to combine tasks.
`CompletableFuture` support both blocking and nonblocking approaches, including regular callbacks.
	
This callback can be executed in another thread as the thread in which the `CompletableFuture` is executed.


The following example demonstrates how to create a basic CompletableFuture.

[source,java]
----
CompletableFuture.supplyAsync(this::doSomething); 
----

`CompletableFuture.supplyAsync` runs the task asynchronously on the default thread pool of Java.
It has the option to supply your custom executor to define the `ThreadPool`.
	
[source,java]
----
include::res/completablefutures/CompletableFutureSimpleSnippet.java[]
----	
	
The usage of the `thenApply` method is demonstrated by the following code snippet.
	
[source,java]
----
include::res/completablefutures/CompletableFutureCallback.java[]
----	

