== Usage of AssertJ

=== Writing assertions

AssertJ assertions start with a call to assertThat followed by an assertion.

[source, java]
----
assertThat("abc").isEqualTo(123);
----

=== Chaining of assertions

AssertJ allows you to be concise by chaining multiple assertions.

[source, java]
----
// JUnit style
assertNotNull(list);
assertTrue(list.isEmpty());

// AssertJ
assertThat(list).isNotNull().isNotEmpty();
----

=== Assertions for Java collections

AssertJ comes with many built in matchers for Java collection classes.

For example the List class:

[source, java]
----
assertThat(userList).contains(user, atIndex(0)).containsOnlyOnce(user, user2, user3);
assertThat(userList).contains(user).isSortedAccordingTo(ageComparator);
----

Here is an example that tests a Map:

[source, java]
----
// check for multiple keys at once
assertThat(map).containsKeys("a", "b", "c");
// check if the value of a certain key satisfies a condition
assertThat(map).hasEntrySatisfying(key, String::isEmpty);
// check if all entries of an other map are contained in a map
assertThat(map).containsAllEntriesOf(expectedSubset);
----

=== Assertions for Date

AssertJ provides special assertions for the Java date class.

[source, java]
----
assertThat(eclipseOxygen.getReleaseDate()).isBeforeYear(2020).isAfterYear(2016);
assertThat(eclipseOxygen.getReleaseDate()).isBetween("2017-01-31", "2017-12-31");
----


=== Assertions for File and Stream

There are assertions to handle common file and stream checks.

[source, java]
----
// file assertions:
assertThat(manifestFile).exists();
assertThat(contentOf(manifestFile)).startsWith("Manifest-Version:");

// stream assertions:
assertThat(streamFromFile).hasSameContentAs(streamFrom(streamFromFileCopy));

=== Adding a custom message to an assertion

We can add a customized message to existing assertions to better explain what we are expecting.
For this purpose we use the `as()` method in our assertion chain:

[source, java]
----
User user = new User("admin");
assertThat(user.getPostCount()).as("User \"%s\" has no posts", user.getName()).isEqualTo(0);
----

=== Comparing objects field by field

Sometimes you don't want to use the existing equals() method but just want to compare by certain fields.
AssertJ provides multiple assertions to help you with that:

[source, java]
----
assertThat(user).isEqualToComparingOnlyGivenFields(otherUser, "address", "age");
----

If you have to problem the classes of certain fields don't implement equals you can use `isEqualToComparingFieldByFieldRecursively`.

[source, java]
----
assertThat(user).isEqualToComparingFieldByFieldRecursively(otherUser);
----

=== Further examples

The following example code is taken from the AssertJ homepage:

[source,java]
----
include::res/start/example.java[]
----
	
