[[cheatsheets]]
== Cheat Sheets

During your Java development time, you will be asked to do certain things, like creating a local variable.
The following can be used as a reference for such tasks, so that you how what you have to do.

[[cheatsheets_class]]
=== Working with classes

While programming Java you have to create several classes, methods, instance variables. 
The following uses the package test.

.Table Title
|===

|What to do |How to do it

|Create a new class called _MyNewClass_.
a|
[source, java]
----
include::res/cheatsheets/MyNewClass1.java[]
----

|Create a new attribute (instance variable) called _var1_ of type `String` in the `MyNewClass` class

a|
[source, java]
----
include::res/cheatsheets/MyNewClass2.java[]
----

|Create a Constructor for your
`MyNewClass`
class which has a
`String`
parameter and assigns the value of it to
the
`var1`
instance
variable.
a|
[source, java]
----
include::res/cheatsheets/MyNewClass3.java[]
----

|Create a new method called
_doSomeThing_
in your class which does not
return a value and has no parameters.

a|
[source, java]
----
include::res/cheatsheets/MyNewClass3a.java[]
----

|Create a new method called
_doSomeThing2_
in your class which does
not
return a value and has two parameters,
an `int`
and a `Person`

a|
[source, java]
----
include::res/cheatsheets/MyNewClass4.java[]
----

|Create a new method called
_doSomeThing3_
in your class which
returns an `int` value and has three parameters,
two `Strings` and a `Person`.

a|
[source, java]
----
include::res/cheatsheets/MyNewClass5.java[]
----

|Create a class called _MyOtherClass_ with two instance
variables.
One will store a `String`, the other will store a `Dog`.
Create
getter and setter for these variables.

a|
[source, java]
----
include::res/cheatsheets/MyOtherClass.java[]
----

|===



[[cheatsheets_localvariable]]
=== Working with local variable

A local variable must always be declared in a method.

.Table Title
|===
|What to do |How to do it

|Declare a (local) variable of type `String`.
a|
[source, java]
----
String variable1;
----

|Declare a (local) variable of type `String` and
assign
`"Test"`
to it.
a|
[source, java]
----
String variable2 = "Test";
----

|Declare a (local) variable of type `Person`
a|
[source, java]
----
Person person;
----

|Declare a (local) variable of type `Person`,
create a new Object and assign the variable to this object.
a|
[source, java]
----
Person person = new Person();
----

|Declare an array of type `String`
a|
[source, java]
----
String array[];
----

|Declare an array of type `Person` and create an array
for this
variable which can hold 5 persons.
a|
[source, java]
----
Person array[]= new Person[5];
----

|Assign 5 to the `int` variable `var1`
(which was already declared);
a|
[source, java]
----
var1 = 5;
----

|Assign the existing variable `pers2` to the existing
variable
`pers1`;
a|
[source, java]
----
pers1 = pers2;
----

|Declare an `ArrayList` variable which can hold objects
of type
`Person`
a|
[source, java]
----
ArrayList<Person> persons
----

|Create a new `ArrayList`
with objects of type `Person`
and
assign it to the existing variable `persons`.
a|
[source, java]
----
persons = new ArrayList<Person>();
----

|Declare an `ArrayList` variable which can hold objects of type `Person` and create a new `Object` for it.
a|
[source, java]
----
ArrayList<Person> persons = new ArrayList<Person>();
----

|===

