[[streams]]
== Streams
[[streams_definition]]
=== What are streams?

A stream from the
`java.util.stream`
package
is
a sequence of elements from a source that
supports
aggregate
operations.

[[stream_intstream]]
=== IntStream
Allow to create a stream of sequence of primitive int-valued
elements supporting sequential and parallel
aggregate operations.

[source,java]
----
include::res/stream/IntStreamExample.java[]
----

[[lambdas_reduction]]
=== Reduction operations with streams and lambdas
Allow to create a stream of sequence of primitive int-valued
elements supporting sequential and parallel
aggregate operations.

[source,java]
----
include::res/stream/Task.java[]
----

[source,java]
----
include::res/stream/StreamTester.java[]
----

[[lambdas_examples]]
=== Example for filtering and mapping the content of a list

The following example demonstrates how to use streams to
filter a list, perform a mapping operation and to
create one
final result string from it with the
`reduce`
method.

[source,java]
----
include::res/stream/JavaStreamExample.java[]
----

[[streams_examples]]
=== Streams and lambda examples

The following is a larger example for the usage of streams. The code is based on the slides from the
https://www.eclipsecon.org/europe2015/session/eclipse-collections-example[Goldmann Sachs Collection presentation at EclipseCOn 2015]

Lets assume the following data model.

[source,java]
----
include::res/stream/PetType.java[]
----

[source,java]
----
include::res/stream/Pet.java[]
----

[source,java]
----
include::res/stream/Person.java[]
----

With this data model you can use streams and lambdas to filter and search the data as demonstrated in the
following example.

[source,java]
----
include::res/stream/Example.java[]
----

