[[javanetwork_overview]]
== Java and HTTP access

(((HTTP access with Java)))
Java provides a HTTP client API to access resources via the HTTP or HTTPS protocol. 
The main classes to access the Internet are the `java.net.URL` class and the `java.net.HttpURLConnection` class.
	
The `URL` class can be used to define a pointer to a web resource while the `HttpURLConnection` class can be used to access a web resource.
	
`HttpURLConnection` allows you to create an `InputStream`.
	
Once you have accessed an `InputStream` you can read it similarly to an `InputStream` from a local file.
	 
`HttpURLConnection` supports the transparent response compression (via the header  `Accept-Encoding: gzip`, Server Name Indication (extension of SSL and TLS) and a response cache.
   
The API is relatively straight forward. For example to retrieve the webpage www.vogella.com you can use the following example.
    
[source,text]
----
include::res/http/get.txt[]
----
    
The Javadoc of `HttpURLConnection` suggest to not reuse an instance of `HttpURLConnection`. 
If you use it this way, `HttpURLConnection` has no threading issues, as it will not be shared between different `Threads`.
    
[NOTE]
====
Alternatively you can also use the scranner class.

[source, language]
----
include::res/http/DowloadWebpageExampleScanner.java[]
----
====
