== Retrofit

(((Retrofit)))
Retrofit is a REST Client for Android and Java by Square.
It makes it relatively easy to retrieve and upload JSON (or other structured data) via a REST based webservice. 
Retrofit can be configured with converter is used for its data serialization. 
Typically for JSON you use GSon, but you can add custom converters to process XML or other protocols.
Retrofit uses the OkHttp library for HTTP requests.

Retrofit allows to use the following converters:

* Gson: com.squareup.retrofit:converter-gson
* Jackson: com.squareup.retrofit:converter-jackson
* Moshi: com.squareup.retrofit:converter-moshi
* Protobuf: com.squareup.retrofit:converter-protobuf
* Wire: com.squareup.retrofit:converter-wire
* Simple XML: com.squareup.retrofit:converter-simplexml

To work with Retrofit you need basically three classes.

* Model class which is used to map the JSON data to
* Interfaces which defines the possible HTTP operations
* Retrofit.Builder class - Instance which uses the interface. 
Builder API which allows defining the URL end point for the HTTP operation.

You can generate Java objects based on JSON via the following URL: http://www.jsonschema2pojo.org/
This can be useful to create complex Java data structures from existing JSON.

