== Retrofit

(((Retrofit)))
Retrofit is a REST Client for Android and Java by Square.
It makes it relatively easy to retrieve and upload JSON (or other structured data) via a REST based webservice. 
Retrofit can be configured with converter is used for its data serialization. 
Typically for JSON you use GSon, but you can add custom converters to process XML or other protocols.
Retrofit uses the OkHttp library for HTTP requests.

Retrofit allows to use the following converters:

* Gson: com.squareup.retrofit:converter-gson
* Jackson: com.squareup.retrofit:converter-jackson
* Moshi: com.squareup.retrofit:converter-moshi
* Protobuf: com.squareup.retrofit:converter-protobuf
* Wire: com.squareup.retrofit:converter-wire
* Simple XML: com.squareup.retrofit:converter-simplexml

To work with Retrofit you need basically three classes.

* Model class which is used to map the JSON data to
* Interfaces which defines the possible HTTP operations
* Retrofit.Builder class - Instance which uses the interface and the Builder API which allows defining the URL end point for the HTTP operation.

==== Define HTTP operations through interfaces
Every method of an interface represents one possible API call.
It must have a HTTP annotation (`GET`, `POST`, etc.) to specify the request type and the relative URL. 
The return value wraps the response in a _Call_ object with the type of the expected result.

....
@GET("users")
Call<List<User>> getUsers()
....

To dynamically change the URL Retrofit supports replacement blocks and query parameters.
A replacement block is added to the relative URL with `{}`. 
With the help of the `@Path` annotation on the method parameter, the value of that parameter is bound to the specific replacement block.

Query parameters are added with the `@Query` annotation on a method parameter. 
They are automatically added at the end of the URL.

The `@Body` annotation on a method parameter tells Retrofit to use the object as the request body for the call.

....
@GET("users/{name}/commits)
Call<List<Commit>> getCommitsByName(@Path("name") String name)

@GET("users")
Call<User> getUserById(@Query("id") Integer id)

@POST("users")
Call<User> postUser(@Body User user)
....



You can generate Java objects based on JSON via the following URL: http://www.jsonschema2pojo.org/
This can be useful to create complex Java data structures from existing JSON.

