== Exercise: Using Retrofit to query Gerrit in Java

The following section describes how to create a minimal Java application which uses Retrofit to query the subjects of open changes from the Gerrit API. 
The results are printed on the console.

=== Project creation and setup

This exercise assumes that you are familiar with http://www.vogella.com/tutorials/Gradle/article.html[Gradle] and http://www.vogella.com/tutorials/EclipseGradle/article.html[Buildship for Eclipse].

Create a new Gradle project with the name _com.vogella.java.retrofitgerrit_.
Add a new package to _src/main/java_ with the name _com.vogella.java.retrofitgerrit_.

Add the following dependencies to your build.gradle file.

[source,xml]
----
include::res/gerrit_java/build.gradle[]
----

=== Define the API and the Retrofit adapter

In the JSON reply from Gerrit we are only interested in the subject of the changes. Therefore create the following data classes in the previously added default package.

[source,java]
----
include::res/gerrit_java/Change.java[]
----

Define the REST API for Retrofit via the following interface.    

[source,java]
----
include::res/gerrit_java/GerritAPI.java[]
----

Create the following controller class. 
This class creates the Retrofit client, calls the Gerrit API and handles the result (prints the result of the call on the console).

[source,java]
----
include::res/gerrit_java/Controller.java[]
----
 
Create a class with a _main_-method to start the controller.

[source,java]
----
include::res/gerrit_java/Main.java[]
----